# Builds the RAG tool's own SUBGRAPH. Mirrors orchestrator/pipeline/graph.py's
# build_graph(llm, tool_router): takes the already-loaded index/llm/sampling_params
# as parameters instead of constructing them itself, so this module's wiring can
# be tested without a GPU (see tests/fake_dependencies.py).
from typing import TYPE_CHECKING

from langgraph.graph import StateGraph, START, END

from tools.ragTool.rag.state import RAGSubgraphState
from tools.ragTool.rag.userQuery import user_query

# Imported only for "VectorStoreIndex"/"LLM"/"SamplingParams" to be resolved 
# as types for string-quoted annotations on build_rag_subgraph
if TYPE_CHECKING:
    from llama_index.core import VectorStoreIndex
    from vllm import LLM, SamplingParams

SYS_PROMPT = (
    "You are a research assitant. Please use the relevant context below to "
    "answer the user's question. If the answer is unclear, reply the fact "
    "that you don't know."
)


def build_rag_subgraph(index: "VectorStoreIndex", llm: "LLM", sampling_params: "SamplingParams"):
    """Assemble and compile the RAG tool's subgraph: extract_query -> retrieve ->
    generate_answer, with an empty-query short-circuit straight to END.

    Compiled with no explicit checkpointer, so it inherits the parent
    orchestrator graph's MemorySaver when run as a node there (LangGraph's
    default subgraph behaviour). This subgraph's own internal state
    (query/retrieved_chunks) is recomputed fresh every call and never needs to
    survive across turns, so inheriting costs a little unnecessary
    serialization -- but it's what keeps this a real, introspectable subgraph:
    compiling with checkpointer=False makes LangGraph's find_subgraph_pregel()
    (langgraph/pregel/_utils.py) treat the node as if it weren't a subgraph at
    all, hiding it from get_graph(xray=True)/get_subgraphs() and anything
    built on those (e.g. LangGraph Studio's subgraph view). Every field here
    is a plain str/list, so the serialization cost is cheap; keep it that way
    if this subgraph's state ever grows.
    """

    graph = StateGraph(RAGSubgraphState)

    # Node: pull the query out of this turn's tool_call.args. If it's missing,
    # also set the same error tool_result the rest of the graph would otherwise
    # have had to special-case downstream -- route_after_extract below sends
    # this straight to END instead of attempting retrieval/generation.
    def extract_query(state: RAGSubgraphState) -> dict:

        query = state["tool_call"].args.get("query", "")

        if not query:
            return {
                "query": query,
                "tool_result": {"output": "RAG tool error: no query was provided.", "relay_verbatim": False},
            }

        return {"query": query}

    # Routing function for the conditional edge below: decides whether there's
    # a query worth retrieving/generating for at all.
    def route_after_extract(state: RAGSubgraphState) -> str:

        return "has_query" if state["query"] else "empty_query"

    # Node: fetch the top matching chunks for this turn's query.
    def retrieve(state: RAGSubgraphState) -> dict:

        retrieved_chunks = user_query(index, state["query"])
        return {"retrieved_chunks": retrieved_chunks}

    # Node: turn the retrieved chunks + query into a generated answer.
    def generate_answer(state: RAGSubgraphState) -> dict:

        context_block = "\n\n".join(
            f"Relevant context {i}:\n{chunk}" for i, chunk in enumerate(state["retrieved_chunks"])
        )

        user_message = f"{SYS_PROMPT}\n\n{context_block}\n\nUser Query:\n{state['query']}"
        messages = [{"role": "user", "content": user_message}]

        try:
            outputs = llm.chat(messages, sampling_params)
        except Exception as e:
            return {"tool_result": {"output": f"RAG tool error: generation failed ({e})", "relay_verbatim": False}}

        answer = outputs[0].outputs[0].text.strip()

        # This answer was already fully generated by the RAG tool's own model,
        # so relay_verbatim=True tells the response-generation step to show it
        # as-is rather than paraphrase/summarize it further.
        return {"tool_result": {"output": answer, "relay_verbatim": True}}

    graph.add_node("extract_query", extract_query)
    graph.add_node("retrieve", retrieve)
    graph.add_node("generate_answer", generate_answer)

    graph.add_edge(START, "extract_query")
    graph.add_conditional_edges(
        "extract_query",
        route_after_extract,
        {
            "has_query": "retrieve",
            "empty_query": END,
        },
    )
    graph.add_edge("retrieve", "generate_answer")
    graph.add_edge("generate_answer", END)

    return graph.compile()
